### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by herpiko** [BlankOn/manokwari#86]
https://github.com/BlankOn/manokwari/pull/85/files#diff-93518fda10b0403d3c5c20b4df4740a6R5

Should begin from a minimalist image like Jessie. Steps : 

- jessie
- dist-upgrade to uluwatu
- install blankon-desktop
- install autoconf, autogen, gnome-common, build-essential and other dev depedencies
- install pyenv (python 3.5.0), nvm (node 8.6.0) and other dev env

Test against `./scripts/deploy.sh`

**Comment by xuvez** [comment]
Can I work on this?

**Comment by herpiko** [comment]
@xuvez Sure! But it seems your comment has been deleted. Do you still want to take this?

**Comment by emhaye** [comment]
* jessie
* dist-upgrade to uluwatu

In our experience you should fix conflict packages like gnome-desktop, evolution a and other packages. This issue is related to different gnome versions of each release.

As an example:
- Jessie uses gnome 3.14
- Uluwatu wear gnome 3.26

This problem also occurs in Tambora and it takes hard work to fix it

*sorry if i'm wrong*

**Comment by herpiko** [comment]
@emhaye The main goal of this issue is to provide a Dockerfile for development purpose, specific to Uluwatu release. It doesn't matter if the build fails, we just have to report it to Uluwatu package maintainers.

It also relevant to provide two Dockerfile. The other one is pointed to Sid directly for outside developer who want to hack on Manokwari.

**Comment by showcheap** [comment]
Close #92
